# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/About.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(510, 443)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(AboutDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 15, -1, 20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nameLabel = QtWidgets.QLabel(AboutDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameLabel.sizePolicy().hasHeightForWidth())
        self.nameLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel.setFont(font)
        self.nameLabel.setText("<html><head/><body><p><span style=\" font-size:20pt;\">PassWordeX v1.0</span></p></body></html>")
        self.nameLabel.setIndent(11)
        self.nameLabel.setObjectName("nameLabel")
        self.horizontalLayout.addWidget(self.nameLabel, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(AboutDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.aboutTab = QtWidgets.QWidget()
        self.aboutTab.setObjectName("aboutTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.aboutTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.aboutTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(0, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem1)
        self.label_8 = QtWidgets.QLabel(self.aboutTab)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.maintainers = QtWidgets.QLabel(self.aboutTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maintainers.sizePolicy().hasHeightForWidth())
        self.maintainers.setSizePolicy(sizePolicy)
        self.maintainers.setText("Gozman Vlad")
        self.maintainers.setOpenExternalLinks(True)
        self.maintainers.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.maintainers.setObjectName("maintainers")
        self.verticalLayout_3.addWidget(self.maintainers)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(self.aboutTab)
        self.pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(AboutDialog.close)
        self.verticalLayout_3.addWidget(self.pushButton, 0, QtCore.Qt.AlignRight)
        self.tabWidget.addTab(self.aboutTab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)

        self.retranslateUi(AboutDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", "Despre PassWordeX"))
        self.label_3.setText(_translate("AboutDialog", "PassWordeX este distribuit în conformitate cu termenii GNU General Public License (GPL) versiunea 2 sau (la opțiunea dvs.) versiunea 3."
                                                       " În lumea digitală oriunde ne uităm, pe majoritatea site-urilor pe care intrăm se poate crea un cont. Pentru acesta este nevoie de un username și o parola. Acestea pot fi reținute dacă vorbim de câteva site-uri, dar dacă deja vorbim de peste 10-20 dintre acestea poate deveni dificil să ne amintim datele de autentificare. Nu este indicat să folosești aceeași parolă pentru fiecare cont deoarece în momentul unei breșe de securitate se va oferi accesul tuturor conturilor ce folosesc aceeași parola. Din acest motiv ar trebui sa avem o parolă diferită pentru fiecare cont. Această aplicație poate genera, la alegerea utilizatorului, o parolă complexă pentru fiecare cont în parte. Dacă se folosește o parolă simplă și comuna există metode precum cea ""BruteForce"" (o entitate malițioasă sau factor extern va încerca un set de combinații până se va nimerii parola). Dacă aceste parole sunt complexe și toate diferite, noi ca oameni nu le putem ține minte și avem nevoie de un loc pentru a le păstra în siguranță și centrat. Un manager de parole cu asta se ocupa, cu păstrarea în siguranță a credidențialelor."))
        self.label_8.setText(_translate("AboutDialog", "Cine mentine proiectul:"))
        self.pushButton.setText(_translate("AboutDialog", "Cancel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.aboutTab), _translate("AboutDialog", "Despre"))
from static import resource_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AboutDialog = QtWidgets.QDialog()
    ui = Ui_AboutDialog()
    ui.setupUi(AboutDialog)
    AboutDialog.show()
    sys.exit(app.exec_())