# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/reportDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 450)
        Dialog.setMaximumSize(QtCore.QSize(650, 450))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameLabel = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameLabel.sizePolicy().hasHeightForWidth())
        self.nameLabel.setSizePolicy(sizePolicy)
        self.nameLabel.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel.setFont(font)
        self.nameLabel.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Raportati problema pe care o aveti!</span></p><p align=\"center\"><span style=\" font-size:12pt;\">- asa vom putea inbunatatii aplicatia -</span></p></body></html>")
        self.nameLabel.setIndent(11)
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout.addWidget(self.nameLabel)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(70, 30, 141, 21))
        self.label.setObjectName("label")
        self.reportComboBox = QtWidgets.QComboBox(self.frame)
        self.reportComboBox.setGeometry(QtCore.QRect(70, 50, 171, 21))
        self.reportComboBox.setObjectName("reportComboBox")
        self.reportComboBox.addItem("")
        self.reportComboBox.addItem("")
        self.reportComboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(70, 70, 271, 31))
        self.label_2.setObjectName("label_2")
        self.ReportTextEdit = QtWidgets.QTextEdit(self.frame)
        self.ReportTextEdit.setGeometry(QtCore.QRect(70, 100, 391, 221))
        self.ReportTextEdit.setObjectName("ReportTextEdit")
        self.verticalLayout.addWidget(self.frame)
        self.Btns = QtWidgets.QDialogButtonBox(Dialog)
        self.Btns.setOrientation(QtCore.Qt.Horizontal)
        self.Btns.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.Btns.setObjectName("Btns")
        self.verticalLayout.addWidget(self.Btns)

        self.retranslateUi(Dialog)
        self.Btns.accepted.connect(Dialog.accept)
        self.Btns.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Reporteaza problema"))
        self.label.setText(_translate("Dialog", "Ce tip de problema aveti?"))
        self.reportComboBox.setItemText(0, _translate("Dialog", "Problema cu interfata"))
        self.reportComboBox.setItemText(1, _translate("Dialog", "Problema cu baza de date"))
        self.reportComboBox.setItemText(2, _translate("Dialog", "Problema cu functiile aplicatiei"))
        self.label_2.setText(_translate("Dialog", "Descrieti in detaliu problema pe care o intampinati:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())